---
- name: Get Disk Usage
  shell: df -h / | awk 'NR==2 {print $5}'
  register: disk_usage
- import_tasks: notification/notify-discord.yaml
  vars:
    msg:
      title: "Disk Usage"
      text: "{{disk_usage.stdout}}"
