---
- name: Send Discord Message
  uri:
    url: "{{discord_url}}"
    method: POST
    body_format: json
    body: {
      "embeds": [
        {
          "title": "{{msg.title}} - {{inventory_hostname}}",
          "description": "{{msg.text}}",
          "color": 23394
        }
      ]
    }
    status_code: 204