---
- hosts: all

  become: true
  tasks:
    # Upgrade 
    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: test part
      include_tasks: test.yaml
