---
- hosts: all

  become: true
  tasks:
    # Upgrade 
    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: check for system reboot
      include_tasks: reboot-required.yaml
