---
- hosts: all

  become: true
  tasks:
    # Upgrade 
    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: get disk space
      include_tasks: disk-space.yaml
