---
- name: Update system
  hosts: all
  become: true
  tasks:
    - name: update packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: include part
      include_tasks: test.yaml
