---
- name: Update System
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    reboot:
      title: "Reboot Required"
      msg: "A reboot is required"
  
  tasks:
    - name: Get Hostnames
      debug:
        msg: "{{ansible_hostname}}:{{ansible_default_ipv4.address}}"

    - name: update apt packages
      apt:
        update_cache: yes

    - name: upgrade apt packages
      apt:
        update_cache: yes

    - name: List installed and updated packages
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result

    - name: Show Output of updated files
      debug: msg="{{ result.stdout_lines }}"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Show Output of required reboots
      debug: msg="{{ reboot.msg }}"
      when: reboot_required_file.stat.exists

    - name: Send Discord Message
      uri:
        url: "{{discord_url}}"
        method: POST
        body_format: json
        body: {
          "embeds": [
            {
              "title": "{{ reboot.title }} - {{ ansible_hostname }}",
              "description": "{{ reboot.msg }} \n Current updates: {{ result.stdout_lines }}",
              "color": 23394
            }
          ]
        }
        status_code: 204
      when: reboot_required_file.stat.exists
