---
- name: Update system
  hosts: all
  gather_facts: yes
  sudo: yes

  vars:
    reboot:
      title: "Reboot Required"
      msg: "A reboot is required"
  
  tasks:
    - name: Get hostnames
      debug:
        msg: "{{ ansible_hostname }}:{{ ansible_default_ipv4.address }}"

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Upgrade apt packages
      apt:
        update_cache: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Show output of required reboots
      debug: msg="{{ reboot.msg }}"
      when: reboot_required_file.stat.exists

    - name: Send discord notification
      uri:
        url: "{{ discord_url }}"
        method: POST
        body_format: json
        body: {
          "embeds": [
            {
              "title": "{{ reboot.title }}",
              "description": "{{ ansible_hostname }} \n {{ reboot.msg }}",
              "color": 23394
            }
          ]
        }
        status_code: 204
      when: reboot_required_file.stat.exists
