---
- hosts: all

  become: true
  tasks:
    # Upgrade 
    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: import disk playbook
      import_playbook: disk-space.yaml
